/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.petshop;

import com.mycompany.petshop.model.Usuario;

/**
 *
 * @author dti
 */
public class Home extends javax.swing.JFrame {

    private Usuario usuarioLogado;

    /**
     * Creates new form Perfil
     */
    public Home() {
        initComponents();
    }

    public Home(Usuario usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
        initComponents();
        verificarPermissoes();
    }

    private void verificarPermissoes() {
        if (!"ADMIN".equals(usuarioLogado.getRole())) {
            menuClientes.setVisible(false);
            menuItemCadastrarServico.setVisible(false);
            menuItemCadastrarProduto.setVisible(false);
            menuItemListarTodosPets.setVisible(false);
            menuItemListarTodosAgendamentos.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        lblTituloPagina = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        Perfil = new javax.swing.JMenu();
        menuItemVisualizarPerfil = new javax.swing.JMenuItem();
        menuItemAlterarPerfil = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuItemListarClientes = new javax.swing.JMenuItem();
        menuServicos = new javax.swing.JMenu();
        menuItemCadastrarServico = new javax.swing.JMenuItem();
        menuItemListarServicos = new javax.swing.JMenuItem();
        menuPets = new javax.swing.JMenu();
        menuItemCadastrarPet = new javax.swing.JMenuItem();
        menuItemListarMeusPets = new javax.swing.JMenuItem();
        menuItemListarTodosPets = new javax.swing.JMenuItem();
        menuAgendamentos = new javax.swing.JMenu();
        menuItemCadastrarAgendamento = new javax.swing.JMenuItem();
        menuItemListarMeusAgendamentos = new javax.swing.JMenuItem();
        menuItemListarTodosAgendamentos = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        menuItemCadastrarProduto = new javax.swing.JMenuItem();
        menuItemListarProdutos = new javax.swing.JMenuItem();
        LogOut = new javax.swing.JMenu();
        menuItemLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloPagina.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloPagina.setText("Bem vindo ao Sistema do Petshop");

        jDesktopPane.setLayer(lblTituloPagina, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTituloPagina)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTituloPagina)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        Perfil.setText("Perfill");

        menuItemVisualizarPerfil.setText("Visualizar");
        menuItemVisualizarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarPerfilActionPerformed(evt);
            }
        });
        Perfil.add(menuItemVisualizarPerfil);

        menuItemAlterarPerfil.setText("Alterar");
        menuItemAlterarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlterarPerfilActionPerformed(evt);
            }
        });
        Perfil.add(menuItemAlterarPerfil);

        menu.add(Perfil);

        menuClientes.setText("Clientes");

        menuItemListarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-listar-cliente.png"))); // NOI18N
        menuItemListarClientes.setText("Listar");
        menuItemListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarClientesActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemListarClientes);

        menu.add(menuClientes);

        menuServicos.setText("Serviços");

        menuItemCadastrarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_plus_new_icon.png"))); // NOI18N
        menuItemCadastrarServico.setText("Cadastrar");
        menuItemCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarServicoActionPerformed(evt);
            }
        });
        menuServicos.add(menuItemCadastrarServico);

        menuItemListarServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-listar-cliente.png"))); // NOI18N
        menuItemListarServicos.setText("Listar");
        menuItemListarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarServicosActionPerformed(evt);
            }
        });
        menuServicos.add(menuItemListarServicos);

        menu.add(menuServicos);

        menuPets.setText("Pets");

        menuItemCadastrarPet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_plus_new_icon.png"))); // NOI18N
        menuItemCadastrarPet.setText("Cadastrar ");
        menuItemCadastrarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarPetActionPerformed(evt);
            }
        });
        menuPets.add(menuItemCadastrarPet);

        menuItemListarMeusPets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-listar-cliente.png"))); // NOI18N
        menuItemListarMeusPets.setText("L istar meus Pets");
        menuItemListarMeusPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarMeusPetsActionPerformed(evt);
            }
        });
        menuPets.add(menuItemListarMeusPets);

        menuItemListarTodosPets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-listar-cliente.png"))); // NOI18N
        menuItemListarTodosPets.setText("Listar todos Pets");
        menuItemListarTodosPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarTodosPetsActionPerformed(evt);
            }
        });
        menuPets.add(menuItemListarTodosPets);

        menu.add(menuPets);

        menuAgendamentos.setText("Agendamentos");

        menuItemCadastrarAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_plus_new_icon.png"))); // NOI18N
        menuItemCadastrarAgendamento.setText("Cadastrar ");
        menuItemCadastrarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarAgendamentoActionPerformed(evt);
            }
        });
        menuAgendamentos.add(menuItemCadastrarAgendamento);

        menuItemListarMeusAgendamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-listar-cliente.png"))); // NOI18N
        menuItemListarMeusAgendamentos.setText("Listar Meus Agendamentos");
        menuItemListarMeusAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarMeusAgendamentosActionPerformed(evt);
            }
        });
        menuAgendamentos.add(menuItemListarMeusAgendamentos);

        menuItemListarTodosAgendamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-listar-cliente.png"))); // NOI18N
        menuItemListarTodosAgendamentos.setText("Listar Todos Agendamentos");
        menuItemListarTodosAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarTodosAgendamentosActionPerformed(evt);
            }
        });
        menuAgendamentos.add(menuItemListarTodosAgendamentos);

        menu.add(menuAgendamentos);

        menuProdutos.setText("Produtos");

        menuItemCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_plus_new_icon.png"))); // NOI18N
        menuItemCadastrarProduto.setText("Cadastrar ");
        menuItemCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarProdutoActionPerformed(evt);
            }
        });
        menuProdutos.add(menuItemCadastrarProduto);

        menuItemListarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-listar-cliente.png"))); // NOI18N
        menuItemListarProdutos.setText("Listar");
        menuItemListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarProdutosActionPerformed(evt);
            }
        });
        menuProdutos.add(menuItemListarProdutos);

        menu.add(menuProdutos);

        LogOut.setText("Log Out");

        menuItemLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-logout.png"))); // NOI18N
        menuItemLogOut.setText("Sair");
        menuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogOutActionPerformed(evt);
            }
        });
        LogOut.add(menuItemLogOut);

        menu.add(LogOut);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarServicoActionPerformed
        CadastrarServico telaCadastrarServico = new CadastrarServico();
        jDesktopPane.add(telaCadastrarServico);
        telaCadastrarServico.setVisible(true);
    }//GEN-LAST:event_menuItemCadastrarServicoActionPerformed

    private void menuItemCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarProdutoActionPerformed
        CadastrarProduto telaCadastrarProduto = new CadastrarProduto();
        jDesktopPane.add(telaCadastrarProduto);
        telaCadastrarProduto.setVisible(true);
    }//GEN-LAST:event_menuItemCadastrarProdutoActionPerformed

    private void menuItemAlterarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlterarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemAlterarPerfilActionPerformed

    private void menuItemVisualizarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemVisualizarPerfilActionPerformed

    private void menuItemListarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarServicosActionPerformed
        ListarServicos telaListarServicos = new ListarServicos();
        jDesktopPane.add(telaListarServicos);
        telaListarServicos.setVisible(true);
    }//GEN-LAST:event_menuItemListarServicosActionPerformed

    private void menuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogOutActionPerformed
        this.dispose();

        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_menuItemLogOutActionPerformed

    private void menuItemListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarClientesActionPerformed
        ListarUsuarios telaListarUsuarios = new ListarUsuarios();
        jDesktopPane.add(telaListarUsuarios);
        telaListarUsuarios.setVisible(true);
    }//GEN-LAST:event_menuItemListarClientesActionPerformed

    private void menuItemListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarProdutosActionPerformed
        ListarProdutos telaListarProdutos = new ListarProdutos();
        jDesktopPane.add(telaListarProdutos);
        telaListarProdutos.setVisible(true);
    }//GEN-LAST:event_menuItemListarProdutosActionPerformed

    private void menuItemCadastrarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarPetActionPerformed
        int idUsuarioLogado = usuarioLogado.getId();
        CadastrarPet telaCadastrarPet = new CadastrarPet(idUsuarioLogado);
        jDesktopPane.add(telaCadastrarPet);
        telaCadastrarPet.setVisible(true);
    }//GEN-LAST:event_menuItemCadastrarPetActionPerformed

    private void menuItemListarMeusPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarMeusPetsActionPerformed
        ListarMeusPets telaListarMeusPets = new ListarMeusPets(usuarioLogado);
        jDesktopPane.add(telaListarMeusPets);
        telaListarMeusPets.setVisible(true);
    }//GEN-LAST:event_menuItemListarMeusPetsActionPerformed

    private void menuItemListarTodosPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarTodosPetsActionPerformed
        ListarTodosPets telaListarTodosPets = new ListarTodosPets();
        jDesktopPane.add(telaListarTodosPets);
        telaListarTodosPets.setVisible(true);
    }//GEN-LAST:event_menuItemListarTodosPetsActionPerformed

    private void menuItemCadastrarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarAgendamentoActionPerformed
        CadastrarAgendamento telaCadastrarAgendamento = new CadastrarAgendamento(usuarioLogado);
        jDesktopPane.add(telaCadastrarAgendamento);
        telaCadastrarAgendamento.setVisible(true);
    }//GEN-LAST:event_menuItemCadastrarAgendamentoActionPerformed

    private void menuItemListarMeusAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarMeusAgendamentosActionPerformed
        ListarMeusAgendamentos telaListarMeusAgendamentos = new ListarMeusAgendamentos(usuarioLogado);
        jDesktopPane.add(telaListarMeusAgendamentos);
        telaListarMeusAgendamentos.setVisible(true);
    }//GEN-LAST:event_menuItemListarMeusAgendamentosActionPerformed

    private void menuItemListarTodosAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarTodosAgendamentosActionPerformed
        ListarTodosAgendamentos telaListarTodosAgendamentos = new ListarTodosAgendamentos();
        jDesktopPane.add(telaListarTodosAgendamentos);
        telaListarTodosAgendamentos.setVisible(true);
    }//GEN-LAST:event_menuItemListarTodosAgendamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu LogOut;
    private javax.swing.JMenu Perfil;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel lblTituloPagina;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAgendamentos;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuItemAlterarPerfil;
    private javax.swing.JMenuItem menuItemCadastrarAgendamento;
    private javax.swing.JMenuItem menuItemCadastrarPet;
    private javax.swing.JMenuItem menuItemCadastrarProduto;
    private javax.swing.JMenuItem menuItemCadastrarServico;
    private javax.swing.JMenuItem menuItemListarClientes;
    private javax.swing.JMenuItem menuItemListarMeusAgendamentos;
    private javax.swing.JMenuItem menuItemListarMeusPets;
    private javax.swing.JMenuItem menuItemListarProdutos;
    private javax.swing.JMenuItem menuItemListarServicos;
    private javax.swing.JMenuItem menuItemListarTodosAgendamentos;
    private javax.swing.JMenuItem menuItemListarTodosPets;
    private javax.swing.JMenuItem menuItemLogOut;
    private javax.swing.JMenuItem menuItemVisualizarPerfil;
    private javax.swing.JMenu menuPets;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuServicos;
    // End of variables declaration//GEN-END:variables
}
